Main svc
Nov-net/java-explore-with-me pull request #2
Opened 2023-02-24 10:23 UTC by Nov-net

2023-02-25 10:07 UTC, SnikerZi requested changes
Привет, Екатерина, ты написала неплохую работу. У меня есть пара предложений по улучшению твоего кода. Желаю успехов в доработке программы. Если у тебя возникнут вопросы по ревью, то ты можешь написать мне в пачке.

2023-02-25 10:07 UTC, SnikerZi commented on ewm-service/src/main/java/ru/practicum/ewm/exception/error/ApiError.java
> +    List<String> errors;
Поля в сериализуемом классе сами должны быть либо сериализуемыми, либо временными, даже если класс никогда явно не сериализуется или не десериализуется. Например, под нагрузкой большинство каркасов приложений J2EE сбрасывают объекты на диск, а предположительно сериализуемый объект с непереходными, несериализуемыми элементами данных может вызвать сбой программы и открыть дверь для злоумышленников. Обычно класс Serializable должен выполнять свой контракт и не иметь неожиданного поведения при сериализации экземпляра.
Это правило вызывает проблему с несериализуемыми полями и полями коллекций, когда они не являются частными (поскольку им могут быть назначены несериализуемые значения извне), и когда им назначаются несериализуемые типы внутри класса.

2023-02-25 10:07 UTC, SnikerZi commented on ewm-service/src/main/java/ru/practicum/ewm/category/dto/CategoryMapper.java
> +
Служебные классы, представляющие собой наборы статических членов, не предназначены для создания экземпляров. Даже абстрактные служебные классы, которые могут быть расширены, не должны иметь общедоступных конструкторов.
Java добавляет неявный общедоступный конструктор к каждому классу, который не определяет хотя бы один явно. Следовательно, должен быть определен по крайней мере один непубличный конструктор.
Это не позволит создавать экземпляры этого класса. 
Пример:
```
private StringUtils() {
    throw new IllegalStateException("Utility class");
  }
```

2023-02-25 10:07 UTC, SnikerZi commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/dto/CompilationMapper.java
> +                .pinned(compilationDto.getPinned() != null ? compilationDto.getPinned() : false)
`.pinned(compilationDto.getPinned() != null && compilationDto.getPinned())
`
Эта конструкция будет получше.
Аналогично для других мест, где у тебя есть подобная конструкция.

2023-02-25 10:07 UTC, SnikerZi commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +    public UpdateStatusRequestResult updateStatusRequest(Long userId, Long eventId, UpdateStatusRequest dto) {
Рекомендую разбить этот метод на несколько приватных методов для облегчения читаемости и понятности кода.

2023-02-25 10:07 UTC, SnikerZi commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +    private Event checkAndSetState(Event event, UpdateEventRequest eventDto) {
Рекомендую разбить этот метод на несколько приватных методов для облегчения читаемости и понятности кода.

2023-02-25 10:07 UTC, SnikerZi commented on ewm-service/src/main/java/ru/practicum/ewm/user/dto/UserMapper.java
> +        User user = User.builder()
Рекомендую сразу возвращать значение

2023-02-26 07:19 UTC, Nov-net commented on ewm-service/src/main/java/ru/practicum/ewm/exception/error/ApiError.java
> +    List<String> errors;
Ростислав, привет!
Спасибо за комменты!
Здесь добавила final

2023-02-26 07:19 UTC, Nov-net commented on ewm-service/src/main/java/ru/practicum/ewm/category/dto/CategoryMapper.java
> +
Добавила @NoArgsConstructor(access = AccessLevel.PRIVATE)

2023-02-26 07:27 UTC, Nov-net commented on ewm-service/src/main/java/ru/practicum/ewm/compilation/dto/CompilationMapper.java
> +                .pinned(compilationDto.getPinned() != null ? compilationDto.getPinned() : false)
исправила, но меня терзают сомнения будет ли в этом случае установлено значение по умолчанию - false

2023-02-26 09:09 UTC, Nov-net commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +    public UpdateStatusRequestResult updateStatusRequest(Long userId, Long eventId, UpdateStatusRequest dto) {
исправила

2023-02-26 09:18 UTC, Nov-net commented on ewm-service/src/main/java/ru/practicum/ewm/event/service/EventServiceImpl.java
> +    private Event checkAndSetState(Event event, UpdateEventRequest eventDto) {
вынесла проверки статуса в отдельные методы

2023-02-26 09:19 UTC, Nov-net commented on ewm-service/src/main/java/ru/practicum/ewm/user/dto/UserMapper.java
> +        User user = User.builder()
исправила

2023-02-26 09:19 UTC, merged